//! Toile Engine — Template Demo (v0.3)
//!
//! Loads a project generated by `toile new` and renders it as a playable game.
//! Demonstrates that project templates produce fully functional scenes.
//!
//! This demo generates a platformer template in-memory (same logic as CLI)
//! then loads and plays the scene with behaviors from prefabs.
//!
//! Controls:
//!   Left/Right arrows: move player
//!   Space: jump
//!   Click: shoot toward cursor
//!   1/2/3/4: switch template (Empty, Platformer, TopDown, Shmup)
//!
//! Run with: `cargo run --example template_demo`

use std::path::Path;

use glam::Vec2;
use toile_app::{App, FontHandle, Game, GameContext, Key, MouseButton as MB, TextureHandle, COLOR_WHITE};
use toile_behaviors::bullet::{self, BulletConfig, BulletState};
use toile_behaviors::fade::{self, FadeConfig, FadeState};
use toile_behaviors::platform::{self, PlatformConfig, PlatformState};
use toile_behaviors::topdown::{self, TopDownConfig};
use toile_behaviors::sine::{self, SineConfig, SineState};
use toile_behaviors::BehaviorConfig;
use toile_behaviors::types::{BehaviorInput, EntityState};
use toile_collision::{overlap_test, Collider};
use toile_core::color::Color;
use toile_graphics::sprite_renderer::{pack_color, DrawSprite};
use toile_scene::prefab::Prefab;
use toile_scene::{EntityData, SceneData};

// ── Runtime entity with resolved behaviors ───────────────────

struct LiveEntity {
    data: EntityData,
    state: EntityState,
    behaviors: Vec<BehaviorConfig>,
    // Behavior states
    platform_state: Option<PlatformState>,
    bullet_state: Option<BulletState>,
    sine_state: Option<SineState>,
    fade_state: Option<FadeState>,
    is_player: bool,
    alive: bool,
}

impl LiveEntity {
    fn from_entity_and_prefab(data: &EntityData, prefab: Option<&Prefab>) -> Self {
        let behaviors: Vec<BehaviorConfig> = prefab
            .map(|p| {
                p.behaviors.iter()
                    .filter_map(|v| serde_json::from_value(v.clone()).ok())
                    .collect()
            })
            .unwrap_or_default();

        let has_platform = behaviors.iter().any(|b| matches!(b, BehaviorConfig::Platform(_)));
        let has_bullet = behaviors.iter().any(|b| matches!(b, BehaviorConfig::Bullet(_)));
        let has_sine = behaviors.iter().any(|b| matches!(b, BehaviorConfig::Sine(_)));
        let is_player = data.name.starts_with("Player");

        Self {
            data: data.clone(),
            state: EntityState {
                position: Vec2::new(data.x, data.y),
                velocity: Vec2::ZERO,
                rotation: data.rotation,
                on_ground: false,
                size: Vec2::new(data.width * data.scale_x, data.height * data.scale_y),
                opacity: 1.0,
                alive: true,
            },
            behaviors,
            platform_state: if has_platform { Some(PlatformState::default()) } else { None },
            bullet_state: if has_bullet { Some(BulletState::default()) } else { None },
            sine_state: if has_sine { Some(SineState::default()) } else { None },
            fade_state: None, // created on demand
            is_player,
            alive: true,
        }
    }
}

struct Projectile {
    state: EntityState,
    bullet_config: BulletConfig,
    bullet_state: BulletState,
    alive: bool,
}

// ── Templates (inline generation) ────────────────────────────

struct TemplateInfo {
    name: &'static str,
    scene: SceneData,
    prefabs: Vec<Prefab>,
}

fn make_entity(id: u64, name: &str, x: f32, y: f32, w: f32, h: f32, layer: i32) -> EntityData {
    EntityData {
        id, name: name.to_string(),
        x, y, rotation: 0.0,
        scale_x: 1.0, scale_y: 1.0,
        layer, sprite_path: String::new(),
        width: w, height: h,
    }
}

fn make_prefab(name: &str, w: f32, h: f32, layer: i32, behaviors: Vec<BehaviorConfig>) -> Prefab {
    Prefab {
        name: name.to_string(),
        entity: make_entity(0, name, 0.0, 0.0, w, h, layer),
        behaviors: behaviors.iter().map(|b| serde_json::to_value(b).unwrap()).collect(),
        event_sheet: None,
    }
}

fn gen_empty() -> TemplateInfo {
    TemplateInfo { name: "Empty", scene: SceneData::new("main"), prefabs: vec![] }
}

fn gen_platformer() -> TemplateInfo {
    let mut scene = SceneData::new("main");
    scene.entities.push(make_entity(1, "Ground", 0.0, -200.0, 1000.0, 30.0, -1));
    scene.entities.push(make_entity(2, "Platform_1", -200.0, -100.0, 120.0, 16.0, -1));
    scene.entities.push(make_entity(3, "Platform_2", 100.0, -20.0, 100.0, 16.0, -1));
    scene.entities.push(make_entity(4, "Platform_3", 300.0, 60.0, 80.0, 16.0, -1));
    scene.entities.push(make_entity(5, "Player", 0.0, -150.0, 24.0, 32.0, 1));
    scene.entities.push(make_entity(6, "Enemy_1", -250.0, -170.0, 28.0, 28.0, 0));
    scene.entities.push(make_entity(7, "Enemy_2", 200.0, -170.0, 28.0, 28.0, 0));
    scene.entities.push(make_entity(8, "Coin_1", -200.0, -70.0, 16.0, 16.0, 0));
    scene.entities.push(make_entity(9, "Coin_2", 100.0, 10.0, 16.0, 16.0, 0));
    scene.entities.push(make_entity(10, "Coin_3", 300.0, 90.0, 16.0, 16.0, 0));
    scene.next_id = 11;

    let prefabs = vec![
        make_prefab("Player", 24.0, 32.0, 1, vec![BehaviorConfig::Platform(PlatformConfig::default())]),
        make_prefab("Enemy", 28.0, 28.0, 0, vec![BehaviorConfig::Fade(FadeConfig { fade_in_time: 0.0, fade_out_time: 0.5, destroy_on_fade_out: true })]),
        make_prefab("Coin", 16.0, 16.0, 0, vec![
            BehaviorConfig::Sine(SineConfig { property: toile_behaviors::sine::SineProperty::Y, magnitude: 5.0, period: 2.0 }),
            BehaviorConfig::Fade(FadeConfig { fade_in_time: 0.0, fade_out_time: 0.3, destroy_on_fade_out: true }),
        ]),
        make_prefab("Platform", 120.0, 16.0, -1, vec![BehaviorConfig::Solid]),
        make_prefab("Ground", 1000.0, 30.0, -1, vec![BehaviorConfig::Solid]),
    ];

    TemplateInfo { name: "Platformer", scene, prefabs }
}

fn gen_topdown() -> TemplateInfo {
    let mut scene = SceneData::new("main");
    scene.entities.push(make_entity(1, "Wall_Top", 0.0, 250.0, 600.0, 20.0, -1));
    scene.entities.push(make_entity(2, "Wall_Bottom", 0.0, -250.0, 600.0, 20.0, -1));
    scene.entities.push(make_entity(3, "Wall_Left", -300.0, 0.0, 20.0, 520.0, -1));
    scene.entities.push(make_entity(4, "Wall_Right", 300.0, 0.0, 20.0, 520.0, -1));
    scene.entities.push(make_entity(5, "Wall_5", -100.0, 100.0, 120.0, 20.0, -1));
    scene.entities.push(make_entity(6, "Wall_6", 100.0, -60.0, 20.0, 120.0, -1));
    scene.entities.push(make_entity(7, "Player", 0.0, 0.0, 24.0, 24.0, 1));
    scene.entities.push(make_entity(8, "Enemy_1", -200.0, -150.0, 24.0, 24.0, 0));
    scene.entities.push(make_entity(9, "Enemy_2", 200.0, 150.0, 24.0, 24.0, 0));
    scene.entities.push(make_entity(10, "Gem_1", 200.0, -150.0, 12.0, 12.0, 0));
    scene.entities.push(make_entity(11, "Gem_2", -50.0, -200.0, 12.0, 12.0, 0));
    scene.next_id = 12;

    let prefabs = vec![
        make_prefab("Player", 24.0, 24.0, 1, vec![BehaviorConfig::TopDown(TopDownConfig::default())]),
        make_prefab("Enemy", 24.0, 24.0, 0, vec![BehaviorConfig::TopDown(TopDownConfig { max_speed: 80.0, ..TopDownConfig::default() })]),
        make_prefab("Wall", 120.0, 20.0, -1, vec![BehaviorConfig::Solid]),
        make_prefab("Gem", 12.0, 12.0, 0, vec![BehaviorConfig::Sine(SineConfig { property: toile_behaviors::sine::SineProperty::Opacity, magnitude: 0.3, period: 1.5 })]),
    ];

    TemplateInfo { name: "Top-Down", scene, prefabs }
}

fn gen_shmup() -> TemplateInfo {
    let mut scene = SceneData::new("main");
    scene.entities.push(make_entity(1, "Player", 0.0, -250.0, 32.0, 24.0, 1));
    for i in 0..5 {
        scene.entities.push(make_entity(2 + i, &format!("Enemy_{}", i + 1), -160.0 + (i as f32) * 80.0, 200.0, 28.0, 28.0, 0));
    }
    for i in 0..3 {
        scene.entities.push(make_entity(7 + i, &format!("Enemy_{}", 6 + i), -80.0 + (i as f32) * 80.0, 280.0, 28.0, 28.0, 0));
    }
    scene.next_id = 10;

    let prefabs = vec![
        make_prefab("Player", 32.0, 24.0, 1, vec![BehaviorConfig::TopDown(TopDownConfig { max_speed: 250.0, acceleration: 2000.0, deceleration: 1500.0, diagonal_correction: true })]),
        make_prefab("Enemy", 28.0, 28.0, 0, vec![
            BehaviorConfig::Bullet(BulletConfig { speed: 60.0, angle_degrees: -90.0, ..BulletConfig::default() }),
            BehaviorConfig::Fade(FadeConfig { fade_in_time: 0.0, fade_out_time: 0.3, destroy_on_fade_out: true }),
        ]),
    ];

    TemplateInfo { name: "Shmup", scene, prefabs }
}

// ── Main game struct ─────────────────────────────────────────

struct TemplateDemo {
    white_tex: Option<TextureHandle>,
    font: Option<FontHandle>,
    template_idx: usize,
    entities: Vec<LiveEntity>,
    projectiles: Vec<Projectile>,
    score: u32,
    status: String,
    template_name: String,
}

fn entity_color(name: &str) -> u32 {
    if name.starts_with("Player") { pack_color(80, 150, 230, 255) }
    else if name.starts_with("Enemy") { pack_color(220, 60, 60, 255) }
    else if name.starts_with("Coin") { pack_color(255, 220, 50, 255) }
    else if name.starts_with("Gem") { pack_color(100, 255, 200, 255) }
    else if name.starts_with("Wall") { pack_color(120, 100, 80, 255) }
    else if name.starts_with("Ground") { pack_color(80, 120, 80, 255) }
    else if name.starts_with("Platform") { pack_color(100, 120, 160, 255) }
    else { pack_color(150, 150, 150, 255) }
}

fn is_solid_entity(name: &str) -> bool {
    name.starts_with("Wall") || name.starts_with("Ground") || name.starts_with("Platform")
}

impl TemplateDemo {
    fn load_template(&mut self, idx: usize) {
        let info = match idx {
            0 => gen_empty(),
            1 => gen_platformer(),
            2 => gen_topdown(),
            3 => gen_shmup(),
            _ => gen_empty(),
        };

        self.template_idx = idx;
        self.template_name = info.name.to_string();
        self.projectiles.clear();
        self.score = 0;

        // Resolve entities with their prefabs
        self.entities = info.scene.entities.iter().map(|e| {
            let prefix = e.name.split('_').next().unwrap_or(&e.name);
            let prefab = info.prefabs.iter().find(|p| p.name == prefix);
            LiveEntity::from_entity_and_prefab(e, prefab)
        }).collect();

        self.status = format!("Template: {} — {} entities loaded", info.name, self.entities.len());
    }

    fn collect_solids(&self) -> Vec<(Vec2, Vec2)> {
        self.entities.iter()
            .filter(|e| e.alive && is_solid_entity(&e.data.name))
            .map(|e| (e.state.position, e.state.size * 0.5))
            .collect()
    }
}

impl Game for TemplateDemo {
    fn init(&mut self, ctx: &mut GameContext) {
        self.white_tex = Some(ctx.load_texture(Path::new("assets/white.png")));
        self.font = Some(ctx.load_ttf(Path::new("assets/fonts/PressStart2P.ttf"), 32.0));
        self.load_template(1); // Start with Platformer
        log::info!("Template Demo! 1=Empty 2=Platformer 3=TopDown 4=Shmup");
    }

    fn update(&mut self, ctx: &mut GameContext, dt: f64) {
        let dt = dt as f32;

        // Switch template
        if ctx.input.is_key_just_pressed(Key::Digit1) { self.load_template(0); return; }
        if ctx.input.is_key_just_pressed(Key::Digit2) { self.load_template(1); return; }
        if ctx.input.is_key_just_pressed(Key::Digit3) { self.load_template(2); return; }
        if ctx.input.is_key_just_pressed(Key::Digit4) { self.load_template(3); return; }

        let input = BehaviorInput {
            left: ctx.input.is_key_down(Key::ArrowLeft) || ctx.input.is_key_down(Key::KeyA),
            right: ctx.input.is_key_down(Key::ArrowRight) || ctx.input.is_key_down(Key::KeyD),
            up: ctx.input.is_key_down(Key::ArrowUp) || ctx.input.is_key_down(Key::KeyW),
            down: ctx.input.is_key_down(Key::ArrowDown) || ctx.input.is_key_down(Key::KeyS),
            jump_pressed: ctx.input.is_key_just_pressed(Key::Space),
            jump_down: ctx.input.is_key_down(Key::Space),
        };

        // Collect solid rects for platform collision
        let solids = self.collect_solids();

        // Update each entity's behaviors
        for entity in &mut self.entities {
            if !entity.alive { continue; }

            for behavior in &entity.behaviors {
                match behavior {
                    BehaviorConfig::Platform(config) => {
                        if let Some(ref mut pstate) = entity.platform_state {
                            let solids = solids.clone();
                            let solid_check = move |pos: Vec2, half: Vec2| -> bool {
                                let col = Collider::aabb(half.x, half.y);
                                for (center, sh) in &solids {
                                    let sc = Collider::aabb(sh.x, sh.y);
                                    if overlap_test(pos, &col, *center, &sc).is_some() {
                                        return true;
                                    }
                                }
                                false
                            };
                            platform::update(config, pstate, &mut entity.state, &input, &solid_check, dt);
                        }
                    }
                    BehaviorConfig::TopDown(config) => {
                        if entity.is_player {
                            topdown::update(config, &mut entity.state, &input, dt);
                            // Wall collision for top-down
                            for (center, sh) in &solids {
                                let col = Collider::aabb(entity.state.size.x * 0.5, entity.state.size.y * 0.5);
                                let sc = Collider::aabb(sh.x, sh.y);
                                if let Some(mtv) = overlap_test(entity.state.position, &col, *center, &sc) {
                                    entity.state.position += mtv;
                                }
                            }
                        }
                    }
                    BehaviorConfig::Bullet(config) => {
                        if !entity.is_player {
                            if let Some(ref mut bstate) = entity.bullet_state {
                                bullet::update(config, bstate, &mut entity.state, dt);
                            }
                        }
                    }
                    BehaviorConfig::Sine(config) => {
                        if let Some(ref mut sstate) = entity.sine_state {
                            sine::update(config, sstate, &mut entity.state, dt);
                        }
                    }
                    BehaviorConfig::Fade(config) => {
                        if let Some(ref mut fstate) = entity.fade_state {
                            fade::update(config, fstate, &mut entity.state, dt);
                        }
                    }
                    _ => {}
                }
            }
        }

        // Player shoot on click
        if ctx.input.is_mouse_just_pressed(MB::Left) {
            if let Some(player) = self.entities.iter().find(|e| e.is_player && e.alive) {
                let mouse_world = ctx.camera.screen_to_world(ctx.input.mouse_position());
                let dir = (mouse_world - player.state.position).normalize_or_zero();
                let angle = dir.y.atan2(dir.x).to_degrees();

                self.projectiles.push(Projectile {
                    state: EntityState {
                        position: player.state.position,
                        velocity: Vec2::ZERO, rotation: 0.0, on_ground: false,
                        size: Vec2::new(8.0, 4.0), opacity: 1.0, alive: true,
                    },
                    bullet_config: BulletConfig { speed: 400.0, angle_degrees: angle, ..Default::default() },
                    bullet_state: BulletState::default(),
                    alive: true,
                });
            }
        }

        // Update projectiles
        for proj in &mut self.projectiles {
            if proj.alive {
                bullet::update(&proj.bullet_config, &mut proj.bullet_state, &mut proj.state, dt);
                if proj.state.position.length() > 800.0 {
                    proj.alive = false;
                }
            }
        }

        // Projectile-enemy collision
        let mut hits = Vec::new();
        for (ei, entity) in self.entities.iter().enumerate() {
            if !entity.alive || entity.is_player || is_solid_entity(&entity.data.name) { continue; }
            if entity.data.name.starts_with("Coin") || entity.data.name.starts_with("Gem") { continue; }
            if entity.fade_state.is_some() { continue; }

            let ec = Collider::aabb(entity.state.size.x * 0.5, entity.state.size.y * 0.5);
            for (pi, proj) in self.projectiles.iter().enumerate() {
                if !proj.alive { continue; }
                let pc = Collider::aabb(proj.state.size.x * 0.5, proj.state.size.y * 0.5);
                if overlap_test(entity.state.position, &ec, proj.state.position, &pc).is_some() {
                    hits.push((ei, pi));
                    break;
                }
            }
        }
        for (ei, pi) in &hits {
            let entity = &mut self.entities[*ei];
            let mut fs = FadeState::default();
            fade::start_fade_out(&mut fs);
            entity.fade_state = Some(fs);
            self.projectiles[*pi].alive = false;
            self.score += 100;
        }
        if !hits.is_empty() {
            self.status = format!("Hit! Score: {}", self.score);
        }

        // Player-collectible collision
        if let Some(player_pos) = self.entities.iter().find(|e| e.is_player && e.alive).map(|e| e.state.position) {
            let player_col = Collider::aabb(12.0, 12.0);
            let mut collects = Vec::new();
            for (i, entity) in self.entities.iter().enumerate() {
                if !entity.alive || entity.fade_state.is_some() { continue; }
                if !entity.data.name.starts_with("Coin") && !entity.data.name.starts_with("Gem") { continue; }
                let ec = Collider::aabb(entity.state.size.x * 0.5, entity.state.size.y * 0.5);
                if overlap_test(player_pos, &player_col, entity.state.position, &ec).is_some() {
                    collects.push(i);
                }
            }
            for i in collects {
                let entity = &mut self.entities[i];
                let mut fs = FadeState::default();
                fade::start_fade_out(&mut fs);
                entity.fade_state = Some(fs);
                self.score += 50;
                self.status = format!("Collected! Score: {}", self.score);
            }
        }

        // Remove dead entities
        self.entities.retain(|e| e.state.alive);
        self.projectiles.retain(|p| p.alive);
    }

    fn draw(&mut self, ctx: &mut GameContext) {
        let tex = match self.white_tex {
            Some(t) => t,
            None => return,
        };

        // Draw all entities
        for entity in &self.entities {
            if !entity.alive { continue; }
            let base_color = entity_color(&entity.data.name);
            let alpha = (entity.state.opacity * 255.0) as u8;
            let color = (base_color & 0x00FFFFFF) | ((alpha as u32) << 24);

            ctx.draw_sprite(DrawSprite {
                texture: tex,
                position: entity.state.position,
                size: entity.state.size,
                rotation: entity.state.rotation,
                color,
                layer: entity.data.layer,
                uv_min: Vec2::ZERO,
                uv_max: Vec2::ONE,
            });
        }

        // Projectiles
        for proj in &self.projectiles {
            ctx.draw_sprite(DrawSprite {
                texture: tex,
                position: proj.state.position,
                size: proj.state.size,
                rotation: proj.bullet_config.angle_degrees.to_radians(),
                color: pack_color(255, 255, 100, 255),
                layer: 4,
                uv_min: Vec2::ZERO,
                uv_max: Vec2::ONE,
            });
        }

        // HUD
        if let Some(font) = self.font {
            let tl = ctx.camera.top_left();
            ctx.draw_text(
                &format!("Template: {} | Score: {}", self.template_name, self.score),
                Vec2::new(tl.x + 10.0, tl.y - 20.0),
                font, 11.0, COLOR_WHITE, 50,
            );
            ctx.draw_text(
                "1:Empty 2:Platformer 3:TopDown 4:Shmup | Arrows=Move Space=Jump Click=Shoot",
                Vec2::new(tl.x + 10.0, tl.y - 38.0),
                font, 5.5, pack_color(150, 150, 170, 255), 50,
            );
            ctx.draw_text(
                &self.status,
                Vec2::new(tl.x + 10.0, tl.y - 52.0),
                font, 6.0, pack_color(100, 200, 100, 255), 50,
            );
        }
    }
}

fn main() {
    App::new()
        .with_title("Toile — Template Demo (v0.3)")
        .with_size(1280, 720)
        .with_clear_color(Color::rgb(0.08, 0.08, 0.12))
        .run(TemplateDemo {
            white_tex: None,
            font: None,
            template_idx: 1,
            entities: Vec::new(),
            projectiles: Vec::new(),
            score: 0,
            status: String::new(),
            template_name: String::new(),
        });
}
